name: Version

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: node version
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Write version